// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCif-F1CPSCnK1xWMY1Owhp26ABLScARH0',
    appId: '1:678178014799:web:d0c3362a8b6a7d8c814c3a',
    messagingSenderId: '678178014799',
    projectId: 'hdict-f9b29',
    authDomain: 'hdict-f9b29.firebaseapp.com',
    storageBucket: 'hdict-f9b29.appspot.com',
    measurementId: 'G-YLL1L8VCS7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTxkanESjBa2oXNlJky5Pg4VyOJ7jGo5M',
    appId: '1:678178014799:android:5286d455ef8740db814c3a',
    messagingSenderId: '678178014799',
    projectId: 'hdict-f9b29',
    storageBucket: 'hdict-f9b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXVloFqz7HRN5YsyRKoXPBJXt2AxHeyok',
    appId: '1:678178014799:ios:82d9ba5314843782814c3a',
    messagingSenderId: '678178014799',
    projectId: 'hdict-f9b29',
    storageBucket: 'hdict-f9b29.appspot.com',
    iosClientId: '678178014799-c62fgm1ibu92qbgbgjacut45d4r5jaj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hdict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXVloFqz7HRN5YsyRKoXPBJXt2AxHeyok',
    appId: '1:678178014799:ios:82d9ba5314843782814c3a',
    messagingSenderId: '678178014799',
    projectId: 'hdict-f9b29',
    storageBucket: 'hdict-f9b29.appspot.com',
    iosClientId: '678178014799-c62fgm1ibu92qbgbgjacut45d4r5jaj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.hdict',
  );
}
